<a href="https://colab.research.google.com/github/SunzidHassan/Tutorials/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Py4e Course

**Chapter 4: Functions**

Function: DRY - Don't repeat yourself

In [ ]:
"""
Write a program to prompt the user for hours and rate per hour using input to compute gross pay.
Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours.
Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value.
Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75).
You should use input to read a string and float() to convert the string to a number.
Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly.
Do not name your variable sum or use the sum() function.
"""

def computepay(h,r):
    if hr < 41:
        p = h*r
        return p
    else:
        p = (40 * r) + ((h-40) * r * 1.5)
        return p

hr = float(input("Enter Hours:"))

rt = float(input("Enter Rate:"))

p = computepay(hr,rt)

print("Pay",p)

**Chapter 7: Files**

In [ ]:
"""
> open(filename, mode) creates a connection with file for python

> '\n' is the newline character

> python reads a file line by line with for loop
file = open('file.txt')
for lines in file:
  print(lines)

file.read() reads the entire file as a long string, with \n as new line characters.

> .starts with checks if a line starts with word of interest
file = open('file.txt')
for lines in file:
  if lines.startswith('word of interest'):
    print('got you')

or

file = open('file.txt')
for lines in file:
  if not lines.startswith('word of interest'): continue
  print('got you')

> prompt user for right file name with try/except. If try not works, except prints a message and quits.

file = input('Enter the file name: ')
try:
  file = open(file)
except:
  print('File can not be opened: ', file)
  quit()
methods

"""

**Chapter 8: Data structures**

In [ ]:
"""
> Lists are collection of data (anything in square brackets)
friends = ['Ador', 'Helal', 'Abhi']

> we can loop through each member of list with for loop
for friend in friends:
  print(friend)

> friend[1] is the second element of friend list

Built in functions
> list.lower() makes the a copy of the list where words lowecase
> len(list) gives length of the list
> range(list) returns list of 0 to number of elements less one of the list
> concatone lists with'+'
> slice list with list[1:3] - meaning take second element to 3rd element (3rd is the 4th element, which isn't included)
> create blank list with list()
> add element at last .append('element')
> 'element' in list (True/False)
> list.sort() - sorts alphabetically
> sum(list) - adds up numbers of list
while Ture:
  inp = input("Engter a number: ")
  if imp == 'done': break
  value = float(inp)
  numlist.append(value)
average = sum(numlist)/len(numlist)
print("Average: ", average)

> abc = 'with three words'
list = abc.split()
list = ['with', 'three', 'words']

abc.split(',') - for comma seperated words

.rstrip() deletes whitespace after word

"""

In [ ]:
# Data structure assignment
"""
Open the file romeo.txt and read it line by line. For each line, split the line into a list of words using the split() method. The program should build a list of words. For each word on each line check to see if the word is already in the list and if not append it to the list. When the program completes, sort and print the resulting words in alphabetical order.
You can download the sample data at http://www.py4e.com/code3/romeo.txt
"""
fname = input("Enter file name: ")
fh = open(fname)
lst = list()
for line in fh:
    wordlist = line.split()
    for word in wordlist:
        if word not in lst: lst.append(word)
lst.sort()
print(lst)

"""
Open the file mbox-short.txt and read it line by line. When you find a line that starts with 'From ' like the following line:
From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
You will parse the From line using split() and print out the second word in the line (i.e. the entire address of the person who sent the message). Then print out a count at the end.
Hint: make sure not to include the lines that start with 'From:'.

You can download the sample data at http://www.py4e.com/code3/mbox-short.txt
"""
fname = input("Enter file name: ")
if len(fname) < 1 : fname = "mbox-short.txt"

fh = open(fname)
count = 0
address = list()

for lines in fh:
    if lines.startswith('From '):
        words = lines.split()
        address.append(words[1])
        count += 1
for addresses in address:
    print(addresses)
print("There were", count, "lines in the file with From as the first word")

**Chapter 9: Dictionaries**

In [ ]:
"""
While lists are ordered elements, dictionary is like a bag full of elements with keys
Everything in a dictionary has a 'value' or 'key'
we can change values, delete them using keys
"""
#creating dictionaries
purse = dict()
purse['money'] = 12 # here, the element is 12, key is 'money'
purse['candy'] = 3 # we add elements with new keys

print(purse)

bag = {'a': 1, 'b': 2, 'c': 3}
bag['d'] = 4
print(bag)

# counting with dictionaries
counter = dict()
counter['john'] = 1
counter['von'] = 1
print(counter)
counter['john'] += 1
print(counter)

"""
# get method: adding new names while counting

counts = dict()
names = ['a', 'b', 'c', 'd']
for name in names:
  counts[name] = counts.get(name, 0) + 1 #0 is the default value assigned to a new name
print(counts)

# what get does
if name not in names:
  counts[name] = 1
else:
  counts[name] += 1

# Loops in dictionary

counts = {'a': 1, 'b': 2, 'c': 3}
for key in counts:
  print(key, counts[key])

# retrieving keys and values as list
counts = {'a': 1, 'b': 2, 'c': 3}
counts.keys()
counts.values()
counts.items() # returns a list of key-value pairs or tuples

for k, v in counts.items:
  print(keys, values)

# code for most common word in a paragraph

file = input('Enter file: ')
handle = open(file)
counts = dict()

for line in handle:
  words = line.split()
  for word in words:
    counts[word] = counts.get(word, 0) + 1

bigcount = None
bigword = None
for k, v in counts.items():
  if bigcount is None or count > bigcount:
    bigword = k
    bigcount = v
print(bigword, bigcount)

"""


In [ ]:
#Dictionary assignment: Write a program to read through the mbox-short.txt and figure out who has sent the greatest number of mail messages.

name = input("Enter file:")
if len(name) < 1 : name = "mbox-short.txt"
handle = open(name)
adrslist = list()

# The program looks for 'From ' lines and takes the second word of those lines as the person who sent the mail.
for lines in handle:
    if lines.startswith('From '):
        parts = lines.split()
        adrslist.append(parts[1])
        
#The program creates a Python dictionary that maps the sender's mail address to a count of the number of times they appear in the file.
adrsdict = dict()
for addresses in adrslist:
    adrsdict[addresses] = adrsdict.get(addresses, 0) + 1

#After the dictionary is produced, the program reads through the dictionary using a maximum loop to find the most prolific committer.
mostmail = None
mostsender = None
for adrs, count in adrsdict.items():
    if mostmail is None or count > mostmail:
        mostsender = adrs
        mostmail = count
print(mostsender, mostmail)

**Chapter 10: Tuples**

In [ ]:
#Tuples are like lists, initiated with parenthesis instead of square brackets

t = ('a', 'b', 'c')
print(t)
print(t[2])

#unlike lists, tuples are immutable, can't be sorted. Because of the restriction, tuples are more efficient

# simultaneous assignment
(x, y) = (4, 'john')
print(x)
print(y)

#tuples comparisons starts from left most elements, and move to compare next item if they're same
# we can create and sort key-value pair tuples of dictionary, and sort them in terms of keys (keys are unique, values need not be)
d = {'a': 1, 'b': 3, 'c': 2}
t = sorted(d.items())
for k, v in sorted(d.items()):
  print(k, v)

# in order to sort values, we need to create new tuples with values, key

tmp = list()
for k, v in d.items():
  tmp.append((v, k))
print(tmp)

tmp = sorted(tmp, reverse=True)
print(tmp)

#10 most common words in a paragraph
"""
handel = open('file.txt')
counts = dict()

for line in handel:
  words = line.split()
  for word in words:
    counts[word] = counts.get(word, 0) + 1

list = list()
for k, v in counts.items():
  newtup = (v, k)
  list.append(newtup)

list = sorted(list, reverse=True)

for v, k in list[:10]:
  print(k, v)

"""

#shorter sorting
"""
d = {'a': 1, 'b': 3, 'c': 2}
print(sorted([(v, k) for k, v in d.items()]))

"""

In [ ]:
#Tuple assignment
"""
Write a program to read through the mbox-short.txt and figure out the distribution by hour of the day for each of the messages.
You can pull the hour out from the 'From ' line by finding the time and then splitting the string a second time using a colon.
From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
Once you have accumulated the counts for each hour, print out the counts, sorted by hour as shown below.

name = input("Enter file:")
if len(name) < 1 : name = "mbox-short.txt"
handle = open(name)

hours= list()

for line in handle:
    if line.startswith('From '):
        l1 = line.split()
        time = l1[5]
        l2 = time.split(':')
        hours.append(l2[0])

hcount = dict()
for hour in hours:


    hcount[hour] = hcount.get(hour, 0) + 1

for h, c in sorted(hcount.items()):
    print(h, c)

"""

**Chapter: ? Object oriented programming**

A lego block of function/code (method) and data (attribute) that does a particular thing. Many such lego blocks can be used to make something useful.

Class is the template that makes class instances or objects.

For example, list is an object (list class can be used to make lists). And list.append() is a class method - that can be used to add element in list.

In [ ]:
"""
Class:
	• Template for objects/instances of class (organized code/method and data/attributes) that are reusable
	• For example, employees of a company has name, email address, salary etc. Each employee are objects, and we can use a class as template to generate the objects.
"""

class Employee:
	
	#this is class variable, which is same for all instances
	raise_amoutn = 1.04
	
	# this is the main class attributes
	def __init__(self, first, last, pay):
		self.first = first
		self.last = last
		self.pay = pay
		self.email = first + '.' + last + '@company.com'
		
	#we can add methods in class
	def fullname(self):
		return '{} {}'.format(self.first, self.last)
		
	def apply_raise(self):
		self.pay = int(self.pay * self.raise_amount)
		# incase of self.class_varialbe, we can change the variable for different instances. But if we had used Employee.raise_amount, then we wont' be able to do that.

# The two employees are two instances of the class.
emp1 = Employee('sunzid', 'hassan', 5000)
emp2 = Employee('sarzil', 'hassan', 6000)

print(Employee.fullname(emp1))
print(emp1.fullname())

"""
A (child) class can inherit capabilities of a previous (parent) class, and build on top of it
A parent class can have different sub classes

class Parent:
	def __init__(self, age)
	do this

class Child(Parent):
	# no def __init__(self), uses parents one
	can do everything as parent
	also, can do this

o = child("Omi")
o.Parent()
O.Chld()
"""



**Chapter 11: Regular expressions**

In [ ]:
"""
^	Matches the beginning of a line
$	Matches the end of the line
.	Matches any character
\s	Matches whitespace
\S	Matches any non-whitespace character
*	Repeats a character zero or more times
*?	Repeats a character zero or more times (non-greedy)
+	Repeats a character one or more times
+?	Repeats a character one or more times (non-greedy)
[aeiou]	Matches a single character in the listed set
[^XYZ]	Matches a single character not in the listed set
[a-z0-9]	The set of characters can include a range
(	Indicates where string extraction is to start
)	Indicates where string extraction is to end

fhand = open('file.txt')
for line in fhand:
  line = line.rstrip()
  if line.startswith('From '):
    print(lines)

import re
fhand = open('file.txt')
for line in fhand:
  line = line.rstrip()
  if re.search('^From:', line): #^means the next character needs to be the first character of the line
    print(line)

^X.*: '.' means any character, '*' means 0 or more characters - so the entire expression means I'm looking for lines that starts with X, and then has any number of characters, then a ':'
^X-\S+: I'm looking for lines that starts with X-, then more than one '+' non blank characters '\S', then ':'

import re
x = 'My 2 favorite numbers are 19 and 42
y = re.findall('[0-9]+', x) # '[0-9]' this is a single character that searches for digists, '+' multiple digits
print(y) # I'll get back a list: ['2', '19', '42']
z = re.findall('[AEIOU]+', x) # find more than one uppercase vowels
print(z) # I'll get back empty list

? is added to make re not greedy

# \s+@\s+ : find more than one none blank char, then @, then more than one non blank char - email address

# re.findall('^From (\s+@\s+)', x): look for 'From email-address, but return just the email-address inside the parenthesis

# we'd manage to find @address with double split, with re, it's '@([^ ]*)' - * for many, [^ ] means not starts with blank

# '^From .*@([^ ]*)' - Start with From-space, then any number of character up to @, then extract all characters up to space

# \$ means I'm looking for $ in string, not re $

import re
hand = open('text.txt')
numlist = list()
for line in hand:
  line = line.rstrip()
  stuff = re.findall('X-DSPAM-Confidence: ([0-9.]+)', line) # extract all digit and '.'
  if len(stuff) != 1: continue # if there are more than 1 numbers, skip the line
  num = float(stuff[0])
  numlist.append(num)
print('Maximum: ', max(numlist))

"""

In [ ]:
#Regular expression assignment

"""
# In this assignment you will read through and parse a file with text and numbers. You will extract all the numbers in the file and compute the sum of the numbers.

import re

hand = open('regex_sum_42.txt')
numlist = list()
for line in hand:
    num = re.findall('[0-9]+', line)
    if len(num) == 0: continue
    for number in num:
        numlist.append(int(number))

print(sum(numlist))

"""

**Chapter 12: Networked Tech**

Computers connect to internet with ports - ports for connecting to web, email etc.

In [ ]:
"""
# Port and socket is used to connect to site (i.e. 80) or email etc
# HTTP is protocol or set of rules through which browser takes data from website
# After setting connection, if you send GET request, server will send back header(metadata), and the contents. Then we receive and decode the data

"""
import socket
mysock = socket.socket(socket.AF_INET, socket.SOCK_STREAM) # we're preparing to connect - this returns an object
mysock.connect(('data.pr4e.org', 80)) # we're actually connecting - in that object, we want the host, and the port 80 to which we want to connect
cmd = 'GET http://data.pr4e.org/romeo.txt HTTP/1.0\r\n\r\n'.encode() # .encode() converts Unicode to UTFA
mysock.send(cmd)

while True:
  data = mysock.recv(512) # we'll receive up to 512 characters at a time
  if (len(data) < 1): break # break if data length is less than 1
  print(data.decode()) # decode from UTFA to unicode
mysock.close()



# Python for Data Science

## Operators

% remainder  
** to the power  
// intefer value of divisor  

_ automatically store the last unassigned variable

%whos returns type of variable

# multiple assignment and automation type assignment
a,b,c,d,e,f = 3,5.5,6.0,-4,2+4j,"hello"

## Bool

T and T is T
T and F is F
F and T is F
F and F is F

T or T is T
T or F is T
F or T is T
F or F is F

== True, if is equal
!= True, if is not equal
<= less than or equal
>= greater than or equal

## useful functions
round(4.6) is 5
round(4.3) is 4
round(4.111,2) is 4.11

divmod(x,y) outputs the quotient and the remainder in a tuple
divmod(27,5) is (5,2)

g = divmod(32,9)
g[0] #first element of g

isinstance(1,(int,float)) is (True, False)

x = input("Enter a number:") #prompts user for an input, default type is 'str'
x = int(x) #convert value of x to integer

or,
x = int(input("Enter a number:"))

pow? will return the documentation of pow function
pow?? will return more information
help(pow) will also return information



# Python for Data Science Specialization

## Python Programming


In [ ]:
#Function with default input
def add_numbers(x, y, z = None):
    if(z == None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))

In [ ]:
##Data Types
#Tuples: immutable

x = (1,'a',2,'b')
type(x)

In [ ]:
#lists: mutable - we can change length, items, values
x = [1, 'a', 2, 'b']

x.append(2.2) #add vlaue at last

#Printing elements
for item in x:
    print(item)

#Printing upto a specific position
i = 0
while(i != len(x)):
    print(x[i])
    i = i+1

# plus sign concatenates lists
x = x + [5, 6]

# '*' sign repeats elements
[1] * 3

# Check if the list has a specific element
1 in [1, 2, 3]

In [ ]:
##Slicing

#with square brackets

x = 'This is a string'
print(x[0]) #print first element
print(x[0:1]) #print first two elements
print(x[-1]) #print last element
print(x[-4:-2]) #print from backwards
print(x[:3]) #print from first to position 4
print(x[3:]) #print from the 4th character


firstName = 'Sunzid'
lastName = 'Hassan'

print(firstName + ' '+ lastName)
print('Sunzid' in firstName)

In [ ]:
# Split

firstName = 'M Sunzid Hassan'.split(' ')[1]
lastName = 'M Sunzid Hassan'.split(' ')[-1]
print(firstName)
print(lastName)

In [ ]:
##Dictionaries: collection of items without order, so we need to label them

x = {'Sunzid Hassan': 'sunzidhassan@gmail.com', 'Slothman': 'ratmanagain@gmail.com'}
x['Sunzid Hassan']

x['live'] = 'sunzidhassan@live.com'
x['live']

for name in x:
    print(x[name])

for email in x.values():
    print(email)

for name, email in x.items():
    print(name)
    print(email)


In [ ]:
# unpack tuple items in variables

x = ('Sunzid', 'Hassan', 'sunzidhassan@gmail.com')
fname, lname, email = x

print(type(x))
print(fname)
print(lname)
print(type(fname))

In [ ]:
## dictionary

# #make a sentence from data in dictionary
sales_record = {'price': 3.24,
                'num_items' : 4,
                'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                                        sales_record['num_items'],
                                        sales_record['price'],
                                        sales_record['num_items']*sales_record['price']))

In [ ]:
#Reading and writing CSV files

import csv

#set precision to 2
%precision 2

#open a csv file in directory
with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

#print first 3 rows
mpg[:3]

#number of rows
len(mpg)

#look at column names
mpg[0].keys()

#average operation
sum(float(d['cty']) for d in mpg) / len(mpg) # we need to convert str data in dictionary to float for mathematical operation

sum(float(d['hwy']) for d in mpg) / len(mpg)

#unique values in a column
cylinders = set(d['cyl'] for d in mpg)

##city fuel economy to number of cylinders relation
CtyMpgByCyl = []

for c in cylinders:
    summpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cyl'] == c:
            summpg += 1
            cyltypecount += 1
    CtyMpgByCyl.append((c, summpg / cyltypecount))

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

##fuel economy across different types of vehicles

#types of vehicles
vehicleClass = set(d['class'] for d in mpg)
vehicleClass

HwyMpgByCLass = []

for t in vehicleClass: #iterate over all vehicle classes
    summpg = 0
    vClassCount = 0
    for d in mpg:
        if d['cass'] == t:
            summpg += float(d['hwy'])
            vClassCount += 1
    HwyMpgByCLass.append((t, summpg / vClassCount)) # append the tuple ('class', 'avg mpg')

HwyMpgByCLass.sort(key = lambda X: x[1]) #probably for ascending sort
HwyMpgByCLass

In [8]:
## Date and time
# Dates are often counted since the Epoch: Jan 1, 1970

import datetime as dt
import time as tm

tm.time() #current time since epoc

dtnow = dt.datetime.fromtimestamp(tm.time())
# tm.time() returns time value since epoch
# dt.datetime returns date and time, fromtimestamp specifies our input

dtnow

# it can returns specific time that we want
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

# time difference
delta = dt.timedelta(days = 100)
today = dt.date.today()
difference = today - delta
print("Date 100 days before is: ", difference) #date 100 days before

Date 100 days before is  2021-12-03


In [ ]:
## Objects and map()

# The first character of class names are usually capitalized
# we can add constructor by using "__init__"

class Person:
    # Class veriables are activated within class instances
    # In this example, all person are assigned department of info within class instances
    department = 'School of Information'

    # we can use methods inside class, which are like using functions inside class
    # however, we need to add 'self' in the input parameters for methods inside classes
    # and we need to add self.variable name for methods
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [ ]:
## Functional programming: paradigm in which we state all parameters which could change during the execution of a function

## Map function
# a built in example of functional programming
# map allows us to apply functions/operations on big data without taking up huge memory.
# In order to check results, we can use for loop

# example 1
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest #this doesn't return the result, rather a map object.
        # it only gives result when we look into it, which allows memory efficiency.

# example 2
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))


In [9]:
## Lambda
# These are anonymous functions - simple (one line) and short lived

# example 1

my_function = lambda a, b, c: a + b
my_function (1, 2, 3)

# example 2
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))


3

In [ ]:
## List comprehension

# example 1: list of even numbers

#option 1
my_list = []
for number in range (0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

# option 2 - list comprehension
# Specify the value we want (number here) followed by condition
my_list = [number for number in range(0, 1000) if number % 2 == 0]


# example 2

def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]

# example 3
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

correct_answer[:50] # Display first 50 ids


### Numpy

In [1]:
import numpy as np
import math

In [2]:
#Arrays are lists or lists of lists

a = np.array([1, 2, 3])
print(a)
print(a.ndim)

1


In [6]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
b.dtype

(2, 3)


dtype('int32')

In [9]:
c = np.array([2.2, 3, 4])
c.dtype.name

#numpy tries to make all entries of an array of the same datatype

'float64'

In [13]:
# arrays of specefic shape with fillers

d = np.zeros((2,3))
e = np.ones((2,3))
f = np.random.rand(2,3)

array([[0.62358271, 0.24757561, 0.43753588],
       [0.88958622, 0.2064488 , 0.0370893 ]])

In [17]:
# Arange function: to create a sequence of numbers in an array. The first argument is starting bound, the second is the ending bound, the third is the difference of each consecutive numbers.

g = np.arange(10, 20, 2)
print(g)

# We use linspace() to create floats. Here the third argument is how many numbers do we want to generate.

h = np.linspace(0, 2, 15)
print(h)

[10 12 14 16 18]
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.        ]


### Array Operations

In [20]:
# We can do mathematical manipulations with arrays (addition, subtraction, square, exponent etc.), boolean arrays, matrix manipulation (product, transpose, inverse, etc.)

# Arithmatic operators apply elementwise

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
c = a-b
print(c)

d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [24]:
new = np.array([10, -20.5, 30.5, -40])
new > 0

# boolean array returns T/F

array([ True, False,  True, False])

In [25]:
new%2 == 0 #if elements are divisible by 2

array([ True, False, False,  True])

In [29]:
# we can do elementwise multiplication with asterix. We can use @ sign for matrix dot multipliaction
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A*B)
print(A@B)

# multiplication of two matrices is only possible when the shape of them are same, and we can use A.shape to get their shape

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


### Pandas

#### Time Series Data: data with column names, that can be retrieved with .name attribute.

In [1]:
import pandas as pd

In [2]:
# We can create a pandas series by passing a list of values.
# Pandas automatically assigns an index starting with zero and sets the name of the series to none.

# Create a list
students = ['Alice', 'Bob', 'Charlie']

# pandas series
pd.Series(students)

0      Alice
1        Bob
2    Charlie
dtype: object

In [3]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [4]:
# Missing data

students = ['Alice', "Bob", None]
pd.Series(students)

0    Alice
1      Bob
2     None
dtype: object

In [5]:
# Pandas considers None as float. Thus, if there are missing data in a column of integers, pandas will treat it as float.

numbers = [1, 2, None]
pd.Series(numbers)

# NaN is not equivalent to None. NaN is numeric, while None is any missing value.

0    1.0
1    2.0
2    NaN
dtype: float64

In [8]:
# a series can be created directly from dictionary. Pandas will automatically use the index as the key, and not just incrementing integers.
students_scores = {'Alice': 'Physics',
                    'Bob': 'Math',
                    'Charlie': 'English'}

s = pd.Series(students_scores)
s

s.index

Index(['Alice', 'Bob', 'Charlie'], dtype='object')

In [9]:
# dtype object is not just for strings

students = [("Alice", "Brown"), ("Jack", "White"), ("Molly", "Green")]
pd.Series(students)

0    (Alice, Brown)
1     (Jack, White)
2    (Molly, Green)
dtype: object

In [12]:
s = pd.Series(['Physics', 'Chemistry', 'English'], index=['Alice', 'Jack', 'Molly'])
s

Alice      Physics
Jack     Chemistry
Molly      English
dtype: object

In [13]:
# If index and keys don't match, pandas will add missing values

students_scores = {'Alice': 'Physics',
                    'Jack': 'Chemistry',
                    'Molly': 'English'}

# Kaggle

## Python

### Functions

In [2]:
def least_difference(a, b, c):
    """Return the smallest difference between any two numbers
    among a, b and c.
    
    >>> least_difference(1, 5, -5)
    4
    """
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    return min(diff1, diff2, diff3)

help(least_difference)

Help on function least_difference in module __main__:

least_difference(a, b, c)
    Return the smallest difference between any two numbers
    among a, b and c.
    
    >>> least_difference(1, 5, -5)
    4



In [ ]:
print(1, 2, 3, sep=' < ')

In [ ]:
#Default values inside function variables

def greet(who="Colin"):
    print("Hello,", who)
    
greet()
greet(who="Kaggle")
# (In this case, we don't need to specify the name of the argument, because it's unambiguous.)
greet("world")

In [ ]:
#Functions within functions

def mult_by_five(x):
    return 5 * x

def call(fn, arg):
    """Call fn on arg"""
    return fn(arg)

def squared_call(fn, arg):
    """Call fn on the result of calling fn on arg"""
    return fn(fn(arg))

print(
    call(mult_by_five, 1),
    squared_call(mult_by_five, 1), 
    sep='\n', # '\n' is the newline character - it starts a new line
)

In [ ]:
# Default arguments

def mod_5(x):
    """Return the remainder of x after dividing by 5"""
    return x % 5

print(
    'Which number is biggest?',
    max(100, 51, 14),
    'Which number is the biggest modulo 5?',
    max(100, 51, 14, key=mod_5),
    sep='\n',
)

### Booleans and Conditionals

In [3]:
True or True and False

True

In [ ]:
#Conditionals
def f(x):
    if x > 0:
        print("Only printed when x is positive; x =", x)
        print("Also only printed when x is positive; x =", x)
    print("Always printed, regardless of x's value; x =", x)

f(1)
f(0)

In [ ]:
print(bool(1)) # all numbers are treated as true, except 0
print(bool(0))
print(bool("asf")) # all strings are treated as true, except the empty string ""
print(bool(""))
# Generally empty sequences (strings, lists, and other types we've yet to see like lists and tuples)
# are "falsey" and the rest are "truthy"

In [ ]:
def wants_plain_hotdog(ketchup, mustard, onion):
    """Return whether the customer wants a plain hot dog with no toppings.
    """
    return not (ketchup or mustard or onion)

In [ ]:
def exactly_one_sauce(ketchup, mustard, onion):
    """Return whether the customer wants either ketchup or mustard, but not both.
    (You may be familiar with this operation under the name "exclusive or")
    """
    return ketchup ^ mustard

In [ ]:
def exactly_one_topping(ketchup, mustard, onion):
    """Return whether the customer wants exactly one of the three available toppings
    on their hot dog.
    """
    return 1 == (int(ketchup) + int(mustard) + int(onion))

### Lists

In [6]:
primes = [2, 3, 5, 7]

planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

hands = [
    ['J', 'Q', 'K'],
    ['2', '2', '2'],
    ['6', 'A', 'K'], # (Comma after the last element is optional)
]

my_favourite_things = [32, 'raindrops on roses', help]

In [ ]:
# Indexing

planets[0]

In [ ]:
planets[-1]

In [11]:
# Slicing
planets[2:]

['Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [9]:
planets[:3]

['Mercury', 'Venus', 'Earth']

In [12]:
# All the planets except the first and last
planets[1:-1]

['Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus']

In [ ]:
# The last 3 planets
planets[-3:]

In [ ]:
# Changing lists
planets[3] = 'Malacandra'
planets

In [13]:
planets[:3] = ['Mur', 'Vee', 'Ur']
print(planets)
# That was silly. Let's give them back their old names
planets[:4] = ['Mercury', 'Venus', 'Earth', 'Mars',]

['Mur', 'Vee', 'Ur', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']


#### List functions

In [ ]:
# The planets sorted in alphabetical order
sorted(planets)

In [ ]:
primes = [2, 3, 5, 7]
sum(primes)

In short, objects carry some things around with them. You access that stuff using Python's dot syntax.

For example, numbers in Python carry around an associated variable called imag representing their imaginary part. (You'll probably never need to use this unless you're doing some very weird math.)

The things an object carries around can also include functions. A function attached to an object is called a method. (Non-function things attached to an object, such as imag, are called attributes).

In the same way that we can pass functions to the help function (e.g. help(max)), we can also pass in methods

In [ ]:
help(x.bit_length)

#### List Methods

In [ ]:
# list.append modifies a list by adding an item to the end:
planets.append('Pluto')

In [ ]:
planets

In [ ]:
# list.pop removes and returns the last element of a list:
planets.pop()

In [ ]:
# Searching lists
planets.index('Earth')

In [ ]:
"Earth" in planets

In [ ]:
"Calbefraques" in planets

#### Tuples
1: The syntax for creating them uses parentheses instead of square brackets

In [ ]:
t = (1, 2, 3)
t = 1, 2, 3 # equivalent to above
t

2: They cannot be modified (they are immutable).

In [ ]:
t[0] = 100

Tuples are often used for functions that have multiple return values.
For example, the as_integer_ratio() method of float objects returns a numerator and a denominator in the form of a tuple:

In [ ]:
x = 0.125
x.as_integer_ratio()

In [ ]:
numerator, denominator = x.as_integer_ratio()

You are analyzing sports teams. Members of each team are stored in a list. The Coach is the first name in the list, the captain is the second name in the list, and other players are listed after that. These lists are stored in another list, which starts with the best team and proceeds through the list to the worst team last. Complete the function below to select the captain of the worst team.

In [14]:
def losing_team_captain(teams):
    """Given a list of teams, where each team is a list of names, return the 2nd player (captain)
    from the last listed team
    """
    return teams[-1][1]

We're using lists to record people who attended our party and what order they arrived in. For example, the following list represents a party with 7 guests, in which Adela showed up first and Ford was the last to arrive:

party_attendees = ['Adela', 'Fleda', 'Owen', 'May', 'Mona', 'Gilbert', 'Ford']
A guest is considered 'fashionably late' if they arrived after at least half of the party's guests. However, they must not be the very last guest (that's taking it too far). In the above example, Mona and Gilbert are the only guests who were fashionably late.

Complete the function below which takes a list of party attendees as well as a person, and tells us whether that person is fashionably late.

In [ ]:
def fashionably_late(arrivals, name):
    """Given an ordered list of arrivals to the party and a name, return whether the guest with that
    name was fashionably late.
    """
    place = arrivals.index(name)
    return (place >= round(len(arrivals)/2)) and (place != len(arrivals)-1)

### Loops and List Comprehensions

The for loop specifies

the variable name to use (in this case, planet)
the set of values to loop over (in this case, planets)
You use the word "in" to link them together.

The object to the right of the "in" can be any object that supports iteration. Basically, if it can be thought of as a group of things, you can probably loop over it. In addition to lists, we can iterate over the elements of a tuple.

In [1]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
for planet in planets:
    print(planet, end=' ') # print all on same line

Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune 

In [2]:
# You can even loop through each character in a string:

s = 'steganograpHy is the practicE of conceaLing a file, message, image, or video within another fiLe, message, image, Or video.'
msg = ''
# print all the uppercase letters in s, one at a time
for char in s:
    if char.isupper():
        print(char, end='')  

HELLO

range()
range() is a function that returns a sequence of numbers. It turns out to be very useful for writing loops.

For example, if we want to repeat some action 5 times:

In [ ]:
for i in range(5):
    print("Doing important work. i =", i)

while loops
The other type of loop in Python is a while loop, which iterates until some condition is met:

In [ ]:
i = 0
while i < 10:
    print(i, end=' ')
    i += 1 # increase the value of i by 1

#### List comprehensions
List comprehensions are one of Python's most beloved and unique features. The easiest way to understand them is probably to just look at a few examples:

In [ ]:
squares = [n**2 for n in range(10)]
squares

In [ ]:
# Here's how we would do the same thing without a list comprehension:

squares = []
for n in range(10):
    squares.append(n**2)
squares

In [3]:
# We can also add an if condition:
short_planets = [planet for planet in planets if len(planet) < 6]
short_planets

['Venus', 'Earth', 'Mars']

(If you're familiar with SQL, you might think of this as being like a "WHERE" clause)

Here's an example of filtering with an if condition and applying some transformation to the loop variable:

In [ ]:
# str.upper() returns an all-caps version of a string
loud_short_planets = [planet.upper() + '!' for planet in planets if len(planet) < 6]
loud_short_planets

In [4]:
# Multiline
[
    planet.upper() + '!'    # Operation
    for planet              # SELECT
    in planets              # FROM
    if len(planet) < 6      # WHERE
]

['VENUS!', 'EARTH!', 'MARS!']

In [ ]:
[32 for planet in planets]

List comprehensions combined with functions like min, max, and sum can lead to impressive one-line solutions for problems that would otherwise require several lines of code.

For example, compare the following two cells of code that do the same thing.

In [ ]:
def count_negatives(nums):
    """Return the number of negative numbers in the given list.
    
    >>> count_negatives([5, -1, -2, 0, 3])
    2
    """
    n_negative = 0
    for num in nums:
        if num < 0:
            n_negative = n_negative + 1
    return n_negative

In [ ]:
def count_negatives(nums):
    """Return the number of negative numbers in the given list.
    
    >>> count_negatives([5, -1, -2, 0, 3])
    2
    """
    return len([num for num in nums if num < 0])

In [ ]:
def count_negatives(nums):
    """Return the number of negative numbers in the given list.
    
    >>> count_negatives([5, -1, -2, 0, 3])
    2
    """
    # Reminder: in the "booleans and conditionals" exercises, we learned about a quirk of 
    # Python where it calculates something like True + True + False + True to be equal to 3.
    return sum([num < 0 for num in nums])

In [ ]:
# Buggy

def has_lucky_number(nums):
    """Return whether the given list of numbers is lucky. A lucky list contains
    at least one number divisible by 7.
    """
    for num in nums:
        if num % 7 == 0:
            return True
        else:
            return False

# Correct
def has_lucky_number(nums):
    """Return whether the given list of numbers is lucky. A lucky list contains
    at least one number divisible by 7.
    """
    if len(nums) > 0:
        for num in nums:
            if num % 7 == 0:
                return True
        return False
    else:
        return False

# Also
def has_lucky_number(nums):
    return any([num % 7 == 0 for num in nums])